# Allure Report Configuration for JMeter
jmeter.reportgenerator.overall_granularity=60000
jmeter.reportgenerator.exporter.allure.classname=io.qameta.allure.jmeter.AllureExporter
jmeter.reportgenerator.outputdir=allure-results
